In [ ]:
import pandas as pd

def main():
    # Create a DataFrame
    data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 22],
        'City': ['New York', 'San Francisco', 'Los Angeles']
    }

    df = pd.DataFrame(data)

    print("Original DataFrame:")
    print(df)

    filtered_df = df[df['Age'] > 25]
    print("\nFiltered DataFrame (Age > 25):")
    print(filtered_df)

if __name__ == "__main__":
    main()


Original DataFrame:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   22    Los Angeles

Filtered DataFrame (Age > 25):
  Name  Age           City
1  Bob   30  San Francisco


In [ ]:
import numpy as np

def main():
    matrix = np.random.rand(3, 3)

    print("Original Matrix:")
    print(matrix)

    transposed_matrix = np.transpose(matrix)
    print("\nTransposed Matrix:")
    print(transposed_matrix)

if __name__ == "__main__":
    main()

Original Matrix:
[[0.74023208 0.37900319 0.14435848]
 [0.96622406 0.38698109 0.20438651]
 [0.09721328 0.09852338 0.56290146]]

Transposed Matrix:
[[0.74023208 0.96622406 0.09721328]
 [0.37900319 0.38698109 0.09852338]
 [0.14435848 0.20438651 0.56290146]]


In [ ]:
install.packages("readr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [ ]:

if (!requireNamespace("readr", quietly = TRUE)) {
  install.packages("readr")
}
library(readr)

file_path <- "/content/sample_data/mnist_test.csv"

data <- read_csv(file_path)
head(data)


New names:
• `0` -> `0...2`
• `0` -> `0...3`
• `0` -> `0...4`
• `0` -> `0...5`
• `0` -> `0...6`
• `0` -> `0...7`
• `0` -> `0...8`
• `0` -> `0...9`
• `0` -> `0...10`
• `0` -> `0...11`
• `0` -> `0...12`
• `0` -> `0...13`
• `0` -> `0...14`
• `0` -> `0...15`
• `0` -> `0...16`
• `0` -> `0...17`
• `0` -> `0...18`
• `0` -> `0...19`
• `0` -> `0...20`
• `0` -> `0...21`
• `0` -> `0...22`
• `0` -> `0...23`
• `0` -> `0...24`
• `0` -> `0...25`
• `0` -> `0...26`
• `0` -> `0...27`
• `0` -> `0...28`
• `0` -> `0...29`
• `0` -> `0...30`
• `0` -> `0...31`
• `0` -> `0...32`
• `0` -> `0...33`
• `0` -> `0...34`
• `0` -> `0...35`
• `0` -> `0...36`
• `0` -> `0...37`
• `0` -> `0...38`
• `0` -> `0...39`
• `0` -> `0...40`
• `0` -> `0...41`
• `0` -> `0...42`
• `0` -> `0...43`
• `0` -> `0...44`
• `0` -> `0...45`
• `0` -> `0...46`
• `0` -> `0...47`
• `0` -> `0...48`
• `0` -> `0...49`
• `0` -> `0...50`
• `0` -> `0...51`
• `0` -> `0...52`
• `0` -> `0...53`
• `0` -> `0...54`
• `0` -> `0...55`
• `0` -> `0...56`
• `0` -

7 0...2 0...3 0...4 0...5 0...6 0...7 0...8 0...9 0...10 ⋯ 0...776 0...777
1 2 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
2 1 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
3 0 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
4 4 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
5 1 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
6 4 0     0     0     0     0     0     0     0     0      ⋯ 0       0      
  0...778 0...779 0...780 0...781 0...782 0...783 0...784 0...785
1 0       0       0       0       0       0       0       0      
2 0       0       0       0       0       0       0       0      
3 0       0       0       0       0       0       0       0      
4 0       0       0       0       0       0       0       0      
5 0       0       0       0       0       0       0       0      
6 0       0       0       0       0       0       0       0

In [ ]:

if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
library(dplyr)

data <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(25, 30, 22),
  City = c("New York", "San Francisco", "Los Angeles")
)

cat("Original Data Frame:\n")
print(data)

filtered_data <- data %>%
  filter(Age > 25) %>%
  mutate(Age_Squared = Age^2)

cat("\nFiltered and Summarized Data:\n")
print(filtered_data)



Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




Original Data Frame:
     Name Age          City
1   Alice  25      New York
2     Bob  30 San Francisco
3 Charlie  22   Los Angeles

Filtered and Summarized Data:
  Name Age          City Age_Squared
1  Bob  30 San Francisco         900
